const REDIRECT_TO_PASSENGER_APP_PROFILE = "https://google.com"
const REDIRECT_TO_PASSENGER_APP_MAIN_TRAVEL = "https://google.com"
const REDIRECT_TO_DRIVER_APP_PROFILE = "https://kjkjhghjasasasasasa.com"
const REDIRECT_TO_OPERATOR_AAP_CHARGE_DRIVER = "https://google.com"

module.exports = {
  REDIRECT_TO_PASSENGER_APP_PROFILE,
  REDIRECT_TO_PASSENGER_APP_MAIN_TRAVEL,
  REDIRECT_TO_DRIVER_APP_PROFILE,
  REDIRECT_TO_OPERATOR_AAP_CHARGE_DRIVER,
}
