const VERIFY_CODE_SENT = 2010
const USER_CREATED = 2011
const USER_UPDATED = 2012
const RESPONSE_SUCCESSFUL = 2013
const PAYMENTS_WERE_MADE = 2014
const RESPONSE_DELETE = 2040
const ERROR_CATEGORY_HAS_CHILDS = 6009
const ERROR_PARAM = 6010
const ERROR_NOT_A_NUMBER = 6011
const ERROR_INVALID_PHONE_NUMBER = 6012
const ERROR_SMS_NOT_SEND = 6013
const ERROR_INVALID_VERIFY_NUMBER = 6014
const ERROR_TOO_MANY_ATTEMPT = 6015
const ERROR_TYPE_NOT_MACH = 6016
const ERROR_TOKEN = 6017
const ERROR_GENDER = 6018
const ERROR_FULL_NAME_MUST_STRING = 6019
const ERROR_WRONG_PARAMETER = 6020
const ERROR_WRONG_PAYMENT_REASON = 6021
const ERROR_DUPLICATE = 6022
const ERROR_NOT_FOUND = 6023
const ERROR_FORBIDDEN = 6024
const ERROR_FINANCIALGROUP_IS_ALREADY_USED = 6025
const ERROR_TRANSACTION_NOT_FOUND = 6026
const ERROR_IN_CALL_BACK_TRANSACTION_PARAM = 6027
const ERROR_UNSUCCESSFUL_PAYMENT = 6028
const ERROR_TARGET_NOT_FOUND = 6029
const ERROR_INSUFFICIENT_BALANCE = 6030
const ERROR_REDIS = 6097
const AUTH_FAILED = 6098
const ERROR_INTERNAL = 6099
const OLD_TRANSACTION = 5100
const ERROR_TRANSACTION = 5101

module.exports = {
  ERROR_CATEGORY_HAS_CHILDS,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  VERIFY_CODE_SENT,
  USER_CREATED,
  PAYMENTS_WERE_MADE,
  USER_UPDATED,
  AUTH_FAILED,
  ERROR_INTERNAL,
  ERROR_PARAM,
  ERROR_NOT_A_NUMBER,
  ERROR_INVALID_PHONE_NUMBER,
  ERROR_INSUFFICIENT_BALANCE,
  ERROR_SMS_NOT_SEND,
  ERROR_INVALID_VERIFY_NUMBER,
  ERROR_TOO_MANY_ATTEMPT,
  ERROR_IN_CALL_BACK_TRANSACTION_PARAM,
  ERROR_TOKEN,
  ERROR_TYPE_NOT_MACH,
  ERROR_REDIS,
  ERROR_GENDER,
  ERROR_TARGET_NOT_FOUND,
  ERROR_FULL_NAME_MUST_STRING,
  ERROR_FINANCIALGROUP_IS_ALREADY_USED,
  ERROR_WRONG_PARAMETER,
  ERROR_WRONG_PAYMENT_REASON,
  ERROR_TRANSACTION_NOT_FOUND,
  RESPONSE_SUCCESSFUL,
  OLD_TRANSACTION,
  ERROR_TRANSACTION,
  ERROR_UNSUCCESSFUL_PAYMENT,
  RESPONSE_DELETE,
  ERROR_DUPLICATE,
}
